sudo: required
services:
  - docker

before_install:
  - docker build -t mukeshranjan03/microservice-docker-react -f Dockerfile.dev .

script:
  - docker run mukeshranjan03/microservice-docker-react npm run test -- --coverage
